/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DuplicateFinder;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author SHAFIN
 */
public class UserInterface extends javax.swing.JFrame
{
    String pathName = "";

    /**
     * Creates new form FileChooser
     */
    public UserInterface()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        filetypeFilter = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AlgoMD5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        CRC32 = new javax.swing.JRadioButton();
        FileAll = new javax.swing.JRadioButton();
        OK = new javax.swing.JButton();
        OpenDir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        duplicatesShow = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        currentStatus = new javax.swing.JTextArea();
        selectedPath = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        AlgoFileSize = new javax.swing.JRadioButton();
        FileInclude = new javax.swing.JRadioButton();
        FileExclude = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duplicate File Finder by SHAFIN_sust_cse_2011331001");

        jLabel3.setText("Duplicate files :");

        jLabel1.setText("Choose Directory");

        jLabel2.setText("Progress Status :");

        jLabel5.setText("File Filtering");

        buttonGroup1.add(AlgoMD5);
        AlgoMD5.setText("Using MD5 Hash");
        AlgoMD5.setToolTipText("Accurate but slower");
        AlgoMD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgoMD5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Chose Algorithm");

        buttonGroup1.add(CRC32);
        CRC32.setText("Using CRC32 Hash");
        CRC32.setToolTipText("little faster than MD5 and Accurate");
        CRC32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRC32ActionPerformed(evt);
            }
        });

        filetypeFilter.add(FileAll);
        FileAll.setText("Just each and every file");

        OK.setText("Start Finding");
        OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClicked(evt);
            }
        });
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        OpenDir.setText("...");
        OpenDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenDirActionPerformed(evt);
            }
        });

        duplicatesShow.setColumns(20);
        duplicatesShow.setRows(5);
        jScrollPane2.setViewportView(duplicatesShow);

        currentStatus.setColumns(20);
        currentStatus.setRows(5);
        jScrollPane4.setViewportView(currentStatus);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(AlgoFileSize);
        AlgoFileSize.setText("Using File Size");
        AlgoFileSize.setToolTipText("faster but error prone");
        AlgoFileSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgoFileSizeActionPerformed(evt);
            }
        });

        filetypeFilter.add(FileInclude);
        FileInclude.setText("Include Only :");
        FileInclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileIncludeActionPerformed(evt);
            }
        });

        filetypeFilter.add(FileExclude);
        FileExclude.setText("Exclude");
        FileExclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileExcludeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(577, 577, 577))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(selectedPath, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addComponent(OpenDir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlgoFileSize)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FileInclude)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(FileExclude)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AlgoMD5))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FileAll)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CRC32)
                                        .addGap(57, 57, 57)
                                        .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(577, 577, 577)
                        .addGap(78, 78, 78)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpenDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileAll)
                    .addComponent(FileInclude)
                    .addComponent(FileExclude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlgoFileSize)
                    .addComponent(AlgoMD5)
                    .addComponent(CRC32)
                    .addComponent(OK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ExitActionPerformed
    {//GEN-HEADEREND:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void OpenDirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OpenDirActionPerformed
    {//GEN-HEADEREND:event_OpenDirActionPerformed
        // display file dialog, so user can choose file or directory to open
        JFileChooser fileChose = new JFileChooser();
        fileChose.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int result = fileChose.showOpenDialog(this);

        // if user clicked Cancel button on dialog, return
        if (result == JFileChooser.CANCEL_OPTION)
        {
            return;
        }

        File fileName = fileChose.getSelectedFile(); // get File

        // display error if invalid
        if ((fileName == null) || (fileName.getName().equals("")))
        {
            JOptionPane.showMessageDialog(this, "Invalid Name",
                    "Invalid Name", JOptionPane.ERROR_MESSAGE);
        }
        pathName = fileName.toString();

        this.selectedPath.setText(pathName);
    }//GEN-LAST:event_OpenDirActionPerformed

    /**
     *
     * @throws Exception
     */
    private void buttonClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buttonClicked
    {//GEN-HEADEREND:event_buttonClicked

        if (pathName == null)
        {
            JOptionPane.showMessageDialog(this, "Choose Directory", "WARNING !", JOptionPane.ERROR_MESSAGE);
        } else
        {
            if (AlgoFileSize.isSelected())
            {
                try
                {
                    String directory = pathName;

                    DFinder listFiles = new DFinder(this, pathName, 1);
                    listFiles.start();

                } catch (Exception e)
                {

                }
            } else if (AlgoMD5.isSelected())
            {
                try
                {
                    String directory = pathName;

                    DFinder listFiles = new DFinder(this, pathName, 2);
                    listFiles.start();

                } catch (Exception e)
                {

                }
            } else if (CRC32.isSelected())
            {
                try
                {
                    String directory = pathName;

                    DFinder listFiles = new DFinder(this, pathName, 3);
                    listFiles.start();

                } catch (Exception e)
                {

                }
            } else
            {
                try
                {
                    String directory = pathName;

                    DFinder listFiles = new DFinder(this, pathName, 1);
                    listFiles.start();

                } catch (Exception e)
                {

                }
            }
        }

    }//GEN-LAST:event_buttonClicked

    private void OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OKActionPerformed
    {//GEN-HEADEREND:event_OKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKActionPerformed

    private void AlgoFileSizeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AlgoFileSizeActionPerformed
    {//GEN-HEADEREND:event_AlgoFileSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlgoFileSizeActionPerformed

    private void AlgoMD5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AlgoMD5ActionPerformed
    {//GEN-HEADEREND:event_AlgoMD5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlgoMD5ActionPerformed

    private void CRC32ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CRC32ActionPerformed
    {//GEN-HEADEREND:event_CRC32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CRC32ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2ActionPerformed
    {//GEN-HEADEREND:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void FileExcludeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FileExcludeActionPerformed
    {//GEN-HEADEREND:event_FileExcludeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileExcludeActionPerformed

    private void FileIncludeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FileIncludeActionPerformed
    {//GEN-HEADEREND:event_FileIncludeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileIncludeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AlgoFileSize;
    private javax.swing.JRadioButton AlgoMD5;
    private javax.swing.JRadioButton CRC32;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JRadioButton FileAll;
    private javax.swing.JRadioButton FileExclude;
    private javax.swing.JRadioButton FileInclude;
    private javax.swing.JButton OK;
    private javax.swing.JButton OpenDir;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextArea currentStatus;
    public javax.swing.JTextArea duplicatesShow;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.ButtonGroup filetypeFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField selectedPath;
    // End of variables declaration//GEN-END:variables
}
